### ISSUE TITLE
replace = for <- in examples

### ISSUE THREAD

**Issue by dirknbr** [stan-dev/example-models#102]
some example (eg https://github.com/stan-dev/example-models/blob/master/misc/moving-avg/arma11.stan) still have <- as an assignment, please make sure example conform to latest version

**Comment by bob-carpenter** [comment]
Thanks for the heads up.  This is a duplicate of #95, so I'm closing.

We're going to take a pass soon and update all the examples.  If you want to fix some of them sooner, we take pull requests.
