### ISSUE TITLE
Failed to build Lotka Vollterra on Mac OS / clang

### ISSUE THREAD

**Issue by marcmenem** [stan-dev/example-models#170]
I tried to build exampe on Mac OS, but it fails with the error message below.
The same file runs fine on Windows. 

I am not sure where to start to investigate the issue. I was having similar errors trying to build models involving the `integrate_ode_rk45` function.

[1] "Error in sampler$call_sampler(args_list[[i]]) : "
[2] "  c++ exception (unknown reason)"                
error occurred during calling the sampler; sampling not done
 [1] "Chain 1: Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:"                        
 [2] "Chain 1: Exception: Max number of iterations exceeded (500).  (in 'modeld45851cc10dc_lotka_volterra' at line 32)"                           
 [3] "Chain 1: If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,"
 [4] "Chain 1: but if this warning occurs often then your model may be either severely ill-conditioned or misspecified."

**Comment by bob-carpenter** [comment]
I think it's an install problem with Stan on Mac OS X.  We've had a ton of problems with Catalina specifically.  I have them ironed out in my Mac OS X Catalina install, and everythig builds OK for me.

**Comment by bob-carpenter** [comment]
Sorry, meant to go on.  Can you try to fit a simple Stan model in the same environment?  I'm afraid I'm not sure where the up-to-date how-to-install-with-Catalina instructions are.

**Comment by mitzimorris** [comment]
what interface are you using?  RStan?

**Comment by marcmenem** [comment]
Thanks Bob. I see it is definitely related to:
https://github.com/stan-dev/rstan/wiki/Catalina-problems

It is confusing because simple models work on a fresh R Kernel, but eventually they can start failing (which is wy I though the issue was with some specific functions.

I'll try to get this sorted out on my install, but any pointers are welcome.

**Comment by marcmenem** [comment]
Yes, using rstan

**Comment by marcmenem** [comment]
FWIW, upgrading to R 4.0 seems to fix the exceptions issue and I was able to run the example, but there I had to turn off parrellel computing because it failed to connect.

**Comment by ssp3nc3r** [comment]
> FWIW, upgrading to R 4.0 seems to fix the exceptions issue and I was able to run the example, but there I had to turn off parrellel computing because it failed to connect.

It's an issue with RStudio and R4.0:

https://github.com/rstudio/rstudio/issues/6692 

You should be able to run parallel chains from the command line, and maybe from RStudio jobs( haven't confirmed the latter yet).

**Comment by bob-carpenter** [comment]
Thanks much for following up.  Sounds like the RStudio team is making this a high priority for a fix after their 1.3 release.

Do you know if this is also a problem with the terminal version of R 4.0, too?

Heads up to the R interface devs: @bgoodri, @jgabry, and @rok-cesnovar, as this may impact RStan and CmdStanR.

**Comment by ssp3nc3r** [comment]
> Do you know if this is also a problem with the terminal version of R 4.0, too?

No, terminal/command line version is fine, as is R Gui. And @bgoodri mentioned that jobs within RStudio may also be fine.
