### ISSUE TITLE
Which book/chapter

### ISSUE THREAD

**Issue by dmcalli2** [stan-dev/example-models#215]
Just wondering which of the texts mentioned in the readme the https://github.com/stan-dev/example-models/blob/master/misc/multivariate-probit/probit-multi.stan model is for. Many thanks.

**Comment by bob-carpenter** [comment]
It's a pretty standard model and the Stan version wasn't derived from any text in particular.  The ones from the texts listed are organized under folders for the texts.  See the top-level directory here:  https://github.com/stan-dev/example-models

ARM, for example, is for the Gelman and Hill Applied Regression Modeling book.
