### ISSUE TITLE
mu_a and mu_b not used?

### ISSUE THREAD

**Issue by dmenne** [stan-dev/example-models#27]
For a problem in 

https://github.com/stan-dev/example-models/blob/master/ARM/Ch.13/pilots.stan

see:
http://stats.stackexchange.com/questions/143359/when-is-mu-a-used-in-this-stan-example

**Comment by bob-carpenter** [comment]
If you wnat to send a pull request, we can merge it.
Otherwise, we need to find someone with some time to take
a pass through all the ARM and BUGS models.  People keep
volunteering then bouncing, so it's still not done.

- Bob

**Comment by dmenne** [comment]
Will do tomorrow.

**Comment by bob-carpenter** [comment]
We should leave the issues open until they're patched, so I'm re-opening.  Thanks.

**Comment by syclik** [comment]
This was fixed with #29.
