### ISSUE TITLE
Possible issue with Viterbi code for HMM example

### ISSUE THREAD

**Issue by frobnitzem** [stan-dev/example-models#31]
In example-models/master/misc/hmm/hmm-semisup.stan, there's an uppercase K rather than a lowercase one when best_logp is initialized.  I'm hoping to fit a 2-category HMM that chooses between Gaussian generalized linear models.

--- hmm-semisup.stan    2015-08-14 00:18:17.000000000 -0400
+++ hmm-semisup.stan2   2015-08-14 00:18:04.000000000 -0400
@@ -48,7 +48,7 @@
     real best_logp[T_unsup,K];
     real best_total_logp;
     for (k in 1:K)
-      best_logp[1,K] <- log(phi[k,u[1]]);
+      best_logp[1,k] <- log(phi[k,u[1]]);
     for (t in 2:T_unsup) {
       for (k in 1:K) {
         best_logp[t,k] <- negative_infinity();

**Comment by bob-carpenter** [comment]
I don't have the full example in front of me, but are you sure that's not just the initialization for the backwards pass?  I'm also confused by the bullets here, but I'm assuming you want them both in a loop?  You can use triple back ticks ` ` ` (but remove space) to open and close code blocks.

**Comment by frobnitzem** [comment]
I believe it is the initialization, but the old line repeatedly initializes best_logp[1,K] at each iteration, making the loop useless.  Didn't realize my post was marked down...
```
--- hmm-semisup.stan    2015-08-14 00:22:29.000000000 -0400
+++ hmm-semisup.stan2   2015-08-14 00:18:04.000000000 -0400
@@ -48,7 +48,7 @@
     real best_logp[T_unsup,K];
     real best_total_logp;
     for (k in 1:K)
-      best_logp[1,K] <- log(phi[k,u[1]]);
+      best_logp[1,k] <- log(phi[k,u[1]]);
     for (t in 2:T_unsup) {
       for (k in 1:K) {
         best_logp[t,k] <- negative_infinity();
```

**Comment by bob-carpenter** [comment]
Thanks.  That's clearer what's going on.  We'll fix it.

**Comment by luisdamiano** [comment]
Hey Bob, just wanted to make you aware that I found the same mistake in [hmm-semisup.stan](https://github.com/stan-dev/example-models/blob/master/misc/hmm/hmm-semisup.stan) Line #51 and [examples.tex](https://github.com/stan-dev/stan/blob/develop/src/docs/stan-reference/examples.tex) Line # 3130 of the reference manual v2.15.0.

**Comment by bob-carpenter** [comment]
@luisdamiano Thanks.  I added a note to the next manual issue:

https://github.com/stan-dev/stan/issues/2336#issuecomment-309816049
