### ISSUE TITLE
Housekeeping: duplicate directory (pool-repeated-trials, pool-binary-trials)

### ISSUE THREAD

**Issue by jonathan-g** [stan-dev/example-models#63]
the folders knitr/pool-binary-trials and knitr/pool-repeated-trials look as though they are identical except that only pool-binary-trials has pool-no-pool.html and only pool-repeated-trials has fit.R.

**Comment by bob-carpenter** [comment]
My mistake.  I'll fix it.

**Comment by bob-carpenter** [comment]
fixed.
